[package]
name = "dead-rose-shell"
version.workspace = true
edition.workspace = true
license.workspace = true

[build-dependencies]
tauri-build = { version = "2.4.0", features = [] }

[dependencies]
dead-rose-ipc = { path = "../../../crates/ipc" }
dead-rose-system-types = { path = "../../../crates/system-types" }
serde.workspace = true
tauri.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-journald.workspace = true
tracing-subscriber.workspace = true

[features]
custom-protocol = ["tauri/custom-protocol"]
