[Distribution]
Distribution=ubuntu
Release=resolute
Repositories=universe
Architecture=x86-64

[Output]
Format=directory
Output=installer-root
OutputDirectory=../../build

[Content]
ExtraTrees=mkosi.extra
Packages=linux-generic
         systemd
         systemd-boot
         cage
         plymouth
         live-boot
         xorriso
         zstd
         ca-certificates
         libwebkit2gtk-4.1-0
         libgtk-3-0
