[Distribution]
Distribution=ubuntu
Release=resolute
Repositories=universe
Architecture=x86-64

[Output]
Format=directory
Output=installer-root
OutputDirectory=../../build
SplitArtifacts=kernel,initrd

[Content]
ExtraTrees=mkosi.extra
InitrdPackages=mount
               util-linux
KernelInitrdModules=isofs
                    squashfs
                    overlay
                    loop
                    ahci
                    sr_mod
                    sd_mod
                    usb-storage
                    uas
                    xhci-pci
                    virtio_blk
                    virtio_pci
Packages=linux-generic
         systemd
         systemd-boot
         dbus
         libpam-systemd
         cage
         plymouth
         xorriso
         zstd
         ca-certificates
         libwebkit2gtk-4.1-0
         libgtk-3-0
