[Distribution]
Distribution=ubuntu
Release=26.04
Architecture=x86-64

[Output]
Format=directory
Output=../../build/installer-root

[Content]
Packages=linux-generic systemd systemd-boot cage plymouth live-boot xorriso zstd ca-certificates libwebkit2gtk-4.1-0 libgtk-3-0
