---
modules-search: [ local ]
instances:
  - id: cleanup
    module: shellprocess
    config: shellprocess-cleanup.conf
  - id: verify
    module: shellprocess
    config: shellprocess-verify.conf
sequence:
  - show:
      - welcome
      - keyboard
      - locale
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - shellprocess@cleanup
      - removeuser
      - users
      - locale
      - keyboard
      - localecfg
      - fstab
      - initcpiocfg
      - initcpio
      - displaymanager
      - networkcfg
      - hwclock
      - services-systemd
      - bootloader
      - packages
      - shellprocess@verify
      - umount
  - show:
      - finished
branding: deadrose
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel-during-exec: true
hide-back-and-next-during-exec: true
