[Unit]
Requires=dead-rose-core.service
After=dead-rose-core.service systemd-user-sessions.service plymouth-quit.service
Conflicts=getty@tty1.service plymouth-quit.service
StartLimitIntervalSec=60s
StartLimitBurst=5

[Service]
Restart=on-failure
RestartSec=5s
