[Unit]
Requires=dead-rose-installer-backend.service
After=dead-rose-installer-backend.service systemd-user-sessions.service
Conflicts=getty@tty1.service plymouth-quit.service plymouth-quit-wait.service
StartLimitIntervalSec=60s
StartLimitBurst=5

[Service]
Environment=DEAD_ROSE_SOFTWARE_RENDERING=1
Environment=WEBKIT_DISABLE_DMABUF_RENDERER=1
Restart=on-failure
RestartSec=5s
