[Distribution]
Distribution=ubuntu
Release=resolute
Repositories=universe
Architecture=x86-64

[Output]
Format=directory
Output=dead-rose-os-root
OutputDirectory=../build

[Content]
Packages=linux-generic
         apt
         systemd
         grub-efi-amd64
         grub-efi-amd64-bin
         grub-efi-amd64-signed
         grub2-common
         efibootmgr
         shim-signed
         systemd-resolved
         dbus
         libpam-systemd
         login
         lsb-release
         greetd
         cage
         plymouth
         mesa-vulkan-drivers
         libgl1-mesa-dri
         ca-certificates
         procps
         libwebkit2gtk-4.1-0
         libgtk-3-0
         libayatana-appindicator3-1
ExtraTrees=mkosi.extra
