[Distribution]
Distribution=ubuntu
Release=resolute
Architecture=x86-64

[Output]
Format=disk
Output=dead-rose-os.raw
OutputDirectory=../build
CompressOutput=false

[Content]
Bootable=yes
Bootloader=systemd-boot
Packages=linux-generic systemd systemd-boot systemd-resolved dbus cage plymouth ca-certificates libwebkit2gtk-4.1-0 libgtk-3-0 libayatana-appindicator3-1
ExtraTrees=mkosi.extra
KernelCommandLine=quiet splash loglevel=3 rd.systemd.show_status=false systemd.show_status=false vt.global_cursor_default=0 ro
