u deadrose-core - "Dead Rose core service" /var/lib/dead-rose -
u deadrose-ui - "Dead Rose graphical shell" /var/lib/dead-rose-ui /usr/sbin/nologin
u deadrose-installer - "Dead Rose installer interface" /var/lib/dead-rose-installer /usr/sbin/nologin
g deadrose-ipc - -
g deadrose-installer-ipc - -
m deadrose-core deadrose-ipc
m deadrose-ui deadrose-ipc
m deadrose-installer deadrose-installer-ipc
