u deadrose-core - "Dead Rose core service" /var/lib/dead-rose -
u deadrose-ui - "Dead Rose graphical shell" /var/lib/dead-rose/ui /usr/sbin/nologin
g deadrose-ipc - -
m deadrose-core deadrose-ipc
m deadrose-ui deadrose-ipc
