d /var/lib/dead-rose 0750 deadrose-core deadrose-core -
d /var/lib/dead-rose/auth 0700 deadrose-core deadrose-core -
d /var/lib/dead-rose/ui 0750 deadrose-ui deadrose-ui -
d /var/lib/dead-rose/installer 0750 deadrose-installer deadrose-installer -
d /run/dead-rose 0750 deadrose-core deadrose-ipc -
d /run/dead-rose-installer 0750 root deadrose-installer-ipc -
