d /var/lib/dead-rose 0750 deadrose-core deadrose-core -
d /var/lib/dead-rose/auth 0700 deadrose-core deadrose-core -
d /var/lib/dead-rose/ui 0750 deadrose-ui deadrose-ui -
d /run/dead-rose 0750 deadrose-core deadrose-ipc -
