---
useSystemdHook: false
source: /usr/share/dead-rose/installed/mkinitcpio.conf
hooks:
  prepend: []
  append: []
  remove: [ archiso, archiso_loop_mnt, archiso_pxe_common, archiso_pxe_nbd, archiso_pxe_http, archiso_pxe_nfs ]
