---
efi:
  mountPoint: /boot/efi
  recommendedSize: 1024MiB
  minimumSize: 512MiB
  label: EFI
initialPartitioningChoice: none
initialSwapChoice: none
userSwapChoices: [ none, small ]
defaultFileSystemType: btrfs
availableFileSystemTypes: [ btrfs ]
allowManualPartitioning: true
luksGeneration: luks1
enableLuksAutomatedPartitioning: true
lvm:
  enable: false
